Additional option to read to the end
mateusjunges/laravel-kafka pull request #103
Opened 2022-05-26 12:31 UTC by StounhandJ

Hi, I really miss such a function, so I decided to try to implement it myself. I am waiting for an answer to how much this option is correct and whether it will be added to the package.

2022-05-30 12:52 UTC, mateusjunges commented
Hi @StounhandJ, can you explain this feature a little bit?

2022-05-30 17:34 UTC, StounhandJ commented
As I planned, she should receive messages from the topic until the last one, as soon as the answer comes that the topic is empty, he will stop his work.

2022-05-30 17:40 UTC, mateusjunges commented
So if I understood correctly, it should stop the consumer as soon as it detects the end of the topic? If so, I think it is better to rename the method from `isReadingToEnd` to `shouldStopAfterLastMessage` and `withReadingToEnd` to `stopAfterLastMessage`. Also, it will be helpful only when reading a topic which already has some messages, because if I create a new topic, create a consumer with this option and start consuming, as soon as the first message is read, the consumer will stop.

2022-05-30 17:43 UTC, StounhandJ commented
That's right. If you think this naming is more correct, then I will rename it. Yes, if you start in a new topic where there are no messages, for example, then he will immediately break through, but I believe in some special tasks it will come in handy.

2022-05-30 17:44 UTC, mateusjunges commented
Ok. Yes, please rename it. Also, is it possible to add test?

2022-05-30 17:46 UTC, StounhandJ commented
I haven't examined the tests in this project yet, so it may take some time.

2022-05-30 17:49 UTC, mateusjunges commented
No problems, on your time.

2022-05-30 17:51 UTC, mateusjunges requested changes

2022-05-30 17:51 UTC, mateusjunges commented on src/Config/Config.php
> +    public function isReadingToEnd(): bool
Please rename it to `shouldStopAfterLastMessage`

2022-05-30 17:51 UTC, mateusjunges commented on src/Consumers/ConsumerBuilder.php
> +    public function withReadingToEnd(bool $readingToEnd = true): self
Rename this to `stopAfterLastMessage`

2022-06-03 14:00 UTC, StounhandJ commented
There is also a question about the [Makefile](https://github.com/mateusjunges/laravel-kafka/blob/v1.7.x/Makefile#L22-L23), since the assembly for testing inside it is outdated, and specifically this [Dockerfile](https://github.com/mateusjunges/laravel-kafka/blob/v1.7.x/dev/Dockerfile#L1)

2022-06-09 08:02 UTC, StounhandJ commented
Unfortunately, I was considering this option. If there is an error in "stopAfterLastMessage", the consume method freezes without the possibility of exiting. May put some expectation in addition to this test.

2022-06-09 19:25 UTC, mateusjunges commented
I think it is worth adding this test, at least we are covering the case when everything works as expected.

2022-06-09 21:28 UTC, StounhandJ commented
What if we try to [use it](https://phpunit.de/manual/6.5/en/risky-tests.html)?

2022-06-09 21:30 UTC, StounhandJ commented
Add annotation @medium

2022-06-10 20:07 UTC, StounhandJ commented
Yes, this is exactly the option I was considering. Unfortunately, I can't run the tests locally, so I won't bother configuring it. I described the [problem](https://github.com/mateusjunges/laravel-kafka/pull/103#issuecomment-1145994834) with running tests above.
In docker-compose-test.yaml also crashes the test container at startup.

2022-06-10 20:09 UTC, mateusjunges commented
The docker image was missing. I've just merged a PR to fix it.

2022-06-13 21:03 UTC, merged