Resolve consumer via service container
mateusjunges/laravel-kafka pull request #118
Opened 2022-07-16 03:44 UTC by cragonnyunt

Resolve consumer using Laravel service container, so that, dependencies can be injected in consumer class.

2022-07-17 18:01 UTC, mateusjunges requested changes

2022-07-17 18:01 UTC, mateusjunges commented on src/Console/Commands/KafkaConsumerCommand.php
> +            consumer: App::make($consumer),
Use the app helper please

2022-07-18 03:11 UTC, cragonnyunt commented on src/Console/Commands/KafkaConsumerCommand.php
> +            consumer: App::make($consumer),
Done, please recheck.

2022-07-20 03:34 UTC, mateusjunges commented
Thank you! I'll merge now but it will be released only when I finish my vacations and arrive home, in two or three days probably.

2022-07-20 03:34 UTC, merged