Add Logger contract to allow end user implement their own Logger
mateusjunges/laravel-kafka pull request #165
Opened 2023-01-06 13:20 UTC by remarkusable

This PR enables the end user to specify their own `Logger` implementation.

There are some use cases where:
- End user want to Log into a file or cloud base logging storage
- End user want to redact some information from the Log, for example PII and GDPR related compliance. At the moment if an Exception occurred and get logged, it might contain the data in the `Message`

2023-01-06 17:31 UTC, mateusjunges requested changes
Hey 👋 Thanks for your PR. Just added a minor change request 🙂

2023-01-08 10:30 UTC, remarkusable commented on src/Logger.php
> +class Logger implements Contracts\Logger
do you want to make it as an Alias or rename the interface file name and move the directory?

2023-01-08 10:35 UTC, remarkusable commented on src/Logger.php
> +class Logger implements Contracts\Logger
looking at your PR for v2, this should be changed into:
```suggestion
class Logger implements Logger
```
and there will be an import for `\Junges\Kafka\Contracts\Logger`

2023-01-10 04:02 UTC, mateusjunges approved these changes
Thanks!

2023-01-10 04:03 UTC, merged

2023-01-10 04:03 UTC, mateusjunges commented
I have to write docs for this so it will be released tomorrow 🙂

2023-01-10 20:21 UTC, mateusjunges commented
Hey @remarkusable just as a FYI, released and documented [here](https://junges.dev/documentation/laravel-kafka/v1.10/advanced-usage/7-custom-loggers)