Waiting for maintenance mode flag
mateusjunges/laravel-kafka pull request #190
Opened 2023-04-06 10:08 UTC by ebrahimradi

2023-04-06 18:39 UTC, mateusjunges requested changes
I like this, but I think it would be better to offer the ability to also run a callback when the consumer detects that the application entered and left maintenance mode. We can define two callbacks that run in this two conditions. Something like this:


```php
if (! app()->isDownForMaintenance()) {
    return;
}

$enteringMaintenanceModeCallback = $this->whenEnterMaintenanceMode;
$enteringMaintenanceModeCallback(...)();

while (app()->isDownForMaintenance()) {
    $sleepTimeInSeconds = random_int(1, 5);
    sleep($sleepTimeInSeconds);
}

$exitingMaintenanceModeCallback = $this->whenExitingMaintenanceMode;
$exitingMaintenanceModeCallback(...)();
```

2023-04-06 18:39 UTC, mateusjunges commented on src/Consumers/Consumer.php
> +                $sleepTime = rand(1, 5);
Why a random delay instead of a const?

2023-04-07 07:21 UTC, ebrahimradi commented on src/Consumers/Consumer.php
> +                $sleepTime = rand(1, 5);
not strong reason! just an example .

2023-04-07 07:24 UTC, ebrahimradi commented
I wanted to apply your suggestion,

I findout a better, more generic idea.
instead of ONLY maintenance mode, we can have  a series of callbacks that can happen before consuming any message. something like middlewares but not related to messages.
then we can have lifecyle for consumer, before, and after. for now we can ignore after, but we can have before callbacks. what's your idea?

2023-04-07 20:26 UTC, mateusjunges commented
Thanks! I have just merged #192 so I'll close this

2023-04-07 20:26 UTC, closed without merging