Multiple kafka broker connections
mateusjunges/laravel-kafka pull request #210
Opened 2023-07-24 13:06 UTC by stefanovik

Hello,

Created a way to configure multiple kafka broker connections, particularly because we've run into a situation where we needed to connect to kafka brokers hosted on our own servers and kafka brokers from Amazon MSK, so we needed this duality.

2023-07-26 06:49 UTC, mihaileu approved these changes

2023-08-07 01:43 UTC, mateusjunges requested changes
Hey! Thanks for your work on this. I have some considerations I'd like you to take a look.

I think a better syntax for this would be to add a new method called `connection`, that let's you specify with which connection you want to work with, instead of adding this feature to the default consumer command only.

Something like this:

```php
Kafka::connection('your-connection-name')->publishOn(...)
```

2023-08-07 01:43 UTC, mateusjunges commented on src/Console/Commands/KafkaConsumerCommand.php
> +                'kafka.connections.' . $this->option('brokerConnection') . '.sasl'
Please use brace syntax here: 

```
"kafka.connections.{$this->option('brokerConnection')}.sasl"
```

2023-08-07 01:43 UTC, mateusjunges commented on src/Console/Commands/KafkaConsumerCommand.php
> +        ) : config('kafka.sasl')) ?? [];
This isn't very readable to me

2023-08-11 11:27 UTC, SergkeiM commented
Hi @stefanovik @mateusjunges 

Added a PR for requested changes by @mateusjunges https://github.com/stefanovik/laravel-kafka/pull/1/files

2023-08-29 11:58 UTC, stefanovik commented
HI @SergkeiM, looking at them right now

2023-10-24 13:16 UTC, mateusjunges commented
Closing this as I don't think this is the best implementation for this feature. I'll think about it a bit and come up with a better API. Thanks for taking the time to implement it tho ❤️

2023-10-24 13:16 UTC, closed without merging