Fixed default securityProtocol
mateusjunges/laravel-kafka pull request #215
Opened 2023-08-14 08:03 UTC by SergkeiM

2023-09-12 09:32 UTC, SergkeiM commented
Hi @mateusjunges did you had a chance to review this PR?

2023-09-12 15:51 UTC, mateusjunges requested changes

2023-09-12 15:51 UTC, mateusjunges commented on src/Console/Commands/KafkaConsumerCommand.php
> +        }, $this->options()), $this->config);
Could you extract this into two lines? It's more readable IMO

2023-09-12 15:52 UTC, mateusjunges commented
Sorry for the delay in reviewing this, I have a lot of things going on ATM

2023-10-24 13:28 UTC, mateusjunges approved these changes

2023-10-24 13:29 UTC, merged