Added support for batch producing and handling batch of messages
mateusjunges/laravel-kafka pull request #86
Opened 2022-03-16 18:16 UTC by vsvp21

2022-03-18 13:08 UTC, mateusjunges commented
I'm wondering why the tests pipeline is not running for this PR

2022-03-18 13:18 UTC, vsvp21 commented
> I'm wondering why the tests pipeline is not running for this PR

I have fixed it, forgot to add extra line at the end of configuration

2022-03-20 19:20 UTC, mateusjunges requested changes

2022-03-20 19:20 UTC, mateusjunges commented on src/BatchRepositories/BatchRepositoryInterface.php
> +interface BatchRepositoryInterface
This class should be in `src/Contracts`

2022-03-20 19:20 UTC, mateusjunges commented on src/BatchRepositories/BatchRepositoryInterface.php
> +declare(strict_types=1);
Please remove strict types from all classes

2022-03-20 19:20 UTC, mateusjunges commented on src/Config/BatchConfigInterface.php
> +namespace Junges\Kafka\Config;
Move this to `src/Contracts`

2022-03-20 19:20 UTC, mateusjunges commented on src/Producers/Producer.php
> +        $messagesIterator->setIteratorMode(\SplDoublyLinkedList::IT_MODE_FIFO);
Please add to the `use` statements

2022-03-20 19:21 UTC, mateusjunges commented
@rtuin can you let me know your thoughts about this?

2022-03-21 05:36 UTC, vsvp21 commented on src/Producers/Producer.php
> +        $messagesIterator->setIteratorMode(\SplDoublyLinkedList::IT_MODE_FIFO);
@mateusjunges fixed

2022-03-21 05:36 UTC, vsvp21 commented on src/Config/BatchConfigInterface.php
> +namespace Junges\Kafka\Config;
@mateusjunges fixed

2022-03-21 05:36 UTC, vsvp21 commented on src/BatchRepositories/BatchRepositoryInterface.php
> +declare(strict_types=1);
@mateusjunges fixed

2022-03-21 05:36 UTC, vsvp21 commented on src/BatchRepositories/BatchRepositoryInterface.php
> +interface BatchRepositoryInterface
@mateusjunges fixed

2022-03-21 13:24 UTC, vsvp21 commented
@mateusjunges should I fix something else? Or it is fine for now?

2022-03-21 13:32 UTC, mateusjunges commented
@vsvp21 one more thing:  can you add a simple PHP doc block at least to the interface methods, explaining what each one is responsible for?

2022-03-21 13:36 UTC, vsvp21 commented
> @vsvp21 i think its fine now. I've just removed some final classes. For my open source code, i assume users know they are responsible for writing tests for any overwritten behaviour. I'll review it one more time later today, and i'll let you know if there is any changes to be made.

Okay, Thanks

2022-03-21 13:37 UTC, vsvp21 commented
> @vsvp21 one more thing: can you add a simple PHP doc block at least to the interface methods, explaining what each one is responsible for?

Yeah I'm gonna add it later today

2022-03-22 04:19 UTC, vsvp21 commented
@mateusjunges I have added PHP doc blocks

2022-03-22 17:14 UTC, mateusjunges commented
I'll merge this later today or tomorrow, i need to update my website to generate the docs from branch `v1.7.x` before. Thank you @vsvp21.

2022-03-22 17:15 UTC, mateusjunges approved these changes

2022-03-23 13:03 UTC, merged